version: "3.8"
services:
  api:
    command: sh -c "npm run dev:api"
    build: .
    image: lifi-fee-collector
    environment:
      NODE_ENV: development
      MONGO_USER: ${MONGO_ROOT_USER}
      MONGO_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_DB: ${MONGO_DB_NAME}
    ports:
      - 8080:8080
    volumes:
      - ./:/home/app
    working_dir: /home/app
    restart: on-failure
    depends_on:
      - database
  fee-update:
    command: sh -c "npm run dev:fee-update"
    image: lifi-fee-collector
    environment:
      NODE_ENV: development
      MONGO_USER: ${MONGO_ROOT_USER}
      MONGO_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_DB: ${MONGO_DB_NAME}
    volumes:
      - ./:/home/app
    working_dir: /home/app
    restart: on-failure
    depends_on:
      - database
      - api
  database:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
